bedrock:
  executable: bedrock_server
  path: ./bedrock-server/bedrock-server-1.21.95.1
logging:
  file_output: false
  file_path: ./logs/server.log
  level: info
server:
  debug: false
  host: localhost
  port: 8080
auth:
  password: "admin123"
  jwt_secret: "your-secret-key-change-this-in-production"
web:
  static_dir: ./web/assets
  template_file: ./web/index.html
  webfonts_dir: ./web/assets/fonts
