bedrock:
  executable: bedrock_server.exe
  path: ""
logging:
  file_output: false
  file_path: ./logs/server.log
  level: info
server:
  debug: false
  host: localhost
  port: 8081
web:
  static_dir: ./web/assets
  template_file: ./web/index.html
  webfonts_dir: ./web/assets/fonts
